name: Build StudentQr Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install nuitka

      - name: Build executable with Nuitka
        run: |
          python -m nuitka --standalone --onefile --enable-plugin=tk-inter --output-filename=StudentQr main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: StudentQr-${{ matrix.os }}
          path: StudentQr*
