name: Build Executables

on:
  workflow_dispatch:  # Run manually from GitHub
  push:
    branches: [main]  # Or run when you push to main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Build executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            nuitka --standalone --onefile --windows-icon-from-ico=icon.ico --output-filename=MyApp.exe your_script.py
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            nuitka --standalone --onefile --macos-app-icon=icon.icns --output-filename=MyApp.app your_script.py
          else
            nuitka --standalone --onefile --output-filename=MyApp.bin your_script.py
          fi

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-MyApp
          path: |
            MyApp.*
