name: Build StudentQr Executable

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [main]  # Auto-build on push to main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            nuitka --standalone --onefile --windows-icon-from-ico=icon.ico --output-filename=StudentQr.exe main.py
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            nuitka --standalone --onefile --macos-app-icon=icon.icns --output-filename=StudentQr.app main.py
          else
            nuitka --standalone --onefile --output-filename=StudentQr.bin main.py
          fi

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-StudentQr
          path: |
            StudentQr.*
